project_id = "andemmyfzzjgegybfrgp"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.submit-payment]
verify_jwt = false
